name: CI Workflow

on:
  push:
    branches-ignore:
      - main  # 忽略 main 分支上的 push
  pull_request:
    types: [closed]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()

  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install uv pytest && uv pip install --system -r requirements.txt

    - name: Install package
      run: pip install -e .

    - name: Run pytest
      run: pytest -s test/
      env:
        GCP_PROJECT_ID: ""
        GCS_BUCKET: ""
        CWA_AUTH_TOKEN: ""

  deploy:
    needs: [pre-commit, pytest]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses:  actions/checkout@v2

    - name: Auth to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_PRIVATE_KEY }}
        project_id: side-project-staging

    - name: Configure Docker for GCP
      run: |
        gcloud auth configure-docker asia-east1-docker.pkg.dev

    - name: Set Docker Image Tag
      run: |
        echo "IMAGE_TAG=asia-east1-docker.pkg.dev/side-project-staging/weather-crawler/codis:${{ github.sha }}" >> $GITHUB_ENV
        echo "IMAGE_LATEST=asia-east1-docker.pkg.dev/side-project-staging/weather-crawler/codis:latest" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build -t ${{ env.IMAGE_TAG }} -t ${{ env.IMAGE_LATEST }} .

    - name: Push Docker Image
      run: |
        docker push ${{ env.IMAGE_TAG }}
        docker push ${{ env.IMAGE_LATEST }}

    - name: Deploy Service
      run: |
        gcloud run deploy weather-crawler-service \
          --image ${{ env.IMAGE_LATEST }} \
          --region asia-east1 \
          --platform managed \
          --service-account ${{ secrets.GCP_SA_ACCOUNT }} \
          --cpu 1 \
          --memory 1Gi \
          --port 8888 \
          --set-secrets CWA_AUTH_TOKEN=codis-api-token:1 \
          --set-env-vars "GCP_PROJECT_ID=side-project-staging,GCS_BUCKET=side-project-weather-data" \
          --max-instances 1 \
          --min-instances 0
